extends Node

func _ready() -> void:
	call_deferred("check_options")

func press(options: Node, code: Key) -> void:
	var event := InputEventKey.new()
	event.physical_keycode = code
	event.pressed = true
	options._input(event)

func check_options() -> void:
	assert(not Save.enabled, "Run with --nosave")
	var main = load("res://scenes/main.tscn").instantiate()
	get_tree().root.add_child(main)
	main.set_process(false)
	var game: Game = main.game
	var options = main.options
	assert(game.TITLE_ITEMS.has("OPTIONS"))
	assert(not game.TITLE_ITEMS.has("RESET") and not game.TITLE_ITEMS.has("RESPEC"))
	game.title_sel = game.TITLE_ITEMS.find("OPTIONS")
	game.activate_title_item()
	assert(options.is_open and not game.is_processing_input())
	assert(options.CATEGORIES.size() == 4)
	for key in options.preferences.EFFECTS:
		options._change(key, false)
	assert(not main.display.env.glow_enabled)
	assert(main.display.lines.wobble == 0.0 and main.display.lines.spike_mult == 0.0)
	assert(main.display.trail_a.render_target_update_mode == SubViewport.UPDATE_DISABLED)
	assert(main.display.screen.material.get_shader_parameter("scan_depth") == 0.0)
	for key in options.preferences.EFFECTS:
		options._change(key, true)
	assert(main.display.settings.crt_curve == options.baseline.crt_curve)
	assert(main.display.trail_a.render_target_update_mode == SubViewport.UPDATE_ALWAYS)
	options._change("volume", 0)
	assert(AudioServer.is_bus_mute(0))
	options._change("volume", 50)
	assert(not AudioServer.is_bus_mute(0))
	assert(is_equal_approx(AudioServer.get_bus_volume_db(0), linear_to_db(0.5)))
	var temporary := ProjectSettings.globalize_path("res://.godot/options-smoke.cfg")
	assert(options.preferences.write_settings(temporary) == OK)
	var reloaded = load("res://scripts/player_settings.gd").new()
	reloaded.read_settings(temporary)
	assert(reloaded.values.volume == 50)
	assert(reloaded.values == options.preferences.values)
	DirAccess.remove_absolute(temporary)
	Save.data.flux = 73
	options._confirm("Reset", "Test", func(): Save.reset_data())
	options.resolve_confirmation()
	assert(Save.data.flux == 73)
	options._confirm("Reset", "Test", func(): Save.reset_data())
	options.confirm_selection = 1
	options.resolve_confirmation()
	assert(Save.data.flux == 0)
	assert(not options.settings_focused, "Options opens on the category list")
	press(options, KEY_DOWN)
	assert(options.category == 1 and options.selection == 0)
	press(options, KEY_ENTER)
	assert(options.settings_focused and options.preferences.values.glow, "Entering a category must not change its first setting")
	press(options, KEY_ENTER)
	assert(not options.preferences.values.glow, "Enter toggles the selected effect")
	press(options, KEY_ENTER)
	assert(options.preferences.values.glow)
	press(options, KEY_DOWN)
	assert(options.selection == 1 and options.category == 1)
	press(options, KEY_LEFT)
	assert(not options.settings_focused and options.preferences.values.trails, "Left returns to categories without changing a value")
	press(options, KEY_DOWN)
	assert(options.category == 2)
	press(options, KEY_ENTER)
	press(options, KEY_ENTER)
	assert(options.adjusting_value and options.preferences.values.volume == 50)
	press(options, KEY_LEFT)
	assert(options.preferences.values.volume == 45 and options.settings_focused)
	press(options, KEY_RIGHT)
	assert(options.preferences.values.volume == 50)
	press(options, KEY_ENTER)
	assert(not options.adjusting_value)
	press(options, KEY_LEFT)
	press(options, KEY_UP)
	assert(options.category == 1 and not options.settings_focused)
	options.select_category(0)
	press(options, KEY_ENTER)
	press(options, KEY_DOWN)
	press(options, KEY_ENTER)
	assert(options.adjusting_value)
	press(options, KEY_RIGHT)
	assert(options.preferences.values.resolution == 2)
	press(options, KEY_LEFT)
	assert(options.preferences.values.resolution == 1)
	press(options, KEY_ESCAPE)
	assert(not options.adjusting_value and options.settings_focused)
	options.preferences.values.fullscreen = true
	press(options, KEY_ENTER)
	assert(not options.adjusting_value, "Disabled resolution must not enter adjustment mode")
	options.preferences.values.fullscreen = false
	options.select_category(3)
	press(options, KEY_ENTER)
	press(options, KEY_ENTER)
	assert(options.pending_action.is_valid() and options.confirm_selection == 0)
	press(options, KEY_ESCAPE)
	assert(not options.pending_action.is_valid() and options.settings_focused)
	press(options, KEY_LEFT)
	press(options, KEY_DOWN)
	assert(options.category == 0, "Category navigation wraps")
	var mouse := InputEventMouseButton.new()
	mouse.button_index = MOUSE_BUTTON_LEFT
	mouse.pressed = true
	mouse.position = options.category_rect(2).get_center()
	options._input(mouse)
	assert(options.category == 2 and not options.settings_focused)
	mouse.position = Vector2(1270, options.row_rect(0).get_center().y)
	options._input(mouse)
	assert(options.preferences.values.volume == 50 and options.settings_focused)
	options.close()
	assert(not options.is_open and game.is_processing_input())
	options.open()
	assert(not options.settings_focused and not options.adjusting_value)
	press(options, KEY_ESCAPE)
	assert(not options.is_open and game.is_processing_input())
	if OS.get_cmdline_user_args().has("--visual"):
		options.open()
		main.fill.visible = false
		for index in 4:
			options.select_category(index)
			main.display.begin_draw()
			options.draw()
			main.display.end_draw()
			for frame in 8:
				await get_tree().process_frame
			await main.display.screenshot("/tmp/options-%d.png" % index)
		options._confirm("RESET JUMP SAVE?", "DELETE ALL JUMP CURRENCIES, UPGRADES, SHIPS AND RECORDS.\nROGUELITE AND OPTIONS ARE KEPT. THIS CANNOT BE UNDONE.", func(): pass)
		main.display.begin_draw()
		options.draw()
		main.display.end_draw()
		for frame in 8:
			await get_tree().process_frame
		await main.display.screenshot("/tmp/options-confirm.png")
	print("OPTIONS SMOKE PASS")
	get_tree().quit()
